[package]
name = "order_book"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.8", features = ["small_rng"] }
crossbeam-channel = "0.5"

[profile.release]
debug = true # Enable debug symbols for profiling

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "order_matching"
harness = false
